[package]
name = "microbit-bsp"
version = "0.3.1"
edition = "2021"
description = "An embassy-based boards support package (BSP) for BBC Micro:bit v2"
license = "MIT OR Apache-2.0"
keywords = ["embedded", "async", "nordic", "nrf", "microbit"]
categories = ["embedded", "hardware-support", "no-std", "asynchronous"]
repository = "https://github.com/lulf/microbit-bsp"

[dependencies]
embassy-nrf = { version = "0.1.0", features = ["nrf52833", "gpiote", "time-driver-rtc1", "nfc-pins-as-gpio", "time", "defmt"]}
embassy-time = { version = "0.3", default-features = false }
embassy-sync = { version = "0.5", default-features = false }
cortex-m = "0.7"
embedded-hal = "1.0"
lsm303agr = "0.3"
defmt = "0.3"
futures = { version = "0.3", default-features = false }
