[package]
name = "microbit-bsp"
version = "0.4.0"
edition = "2021"
description = "An embassy-based boards support package (BSP) for BBC Micro:bit v2"
license = "MIT OR Apache-2.0"
keywords = ["embedded", "async", "nordic", "nrf", "microbit"]
categories = ["embedded", "hardware-support", "no-std", "asynchronous"]
repository = "https://github.com/lulf/microbit-bsp"


[dependencies]
embassy-nrf = { version = "0.2.0", features = ["nrf52833","gpiote","time-driver-rtc1","nfc-pins-as-gpio","time"] }
embassy-time = { version = "0.3", default-features = false }
embassy-sync = { version = "0.6", default-features = false }
cortex-m = "0.7"
embedded-hal = "1.0"
lsm303agr = "1.1.0"
futures = { version = "0.3", default-features = false }
defmt = { version = "0.3", optional = true }
heapless = "0.8.0"

# trouble bluetooth dependencies
nrf-sdc = { version = "0.1.0", default-features = false, features = ["defmt", "peripheral", "central", "nrf52833"], optional = true}
nrf-mpsl = { version = "0.1.0", default-features = false, features = ["defmt", "critical-section-impl"], optional = true }
static_cell = { version = "2", optional = true }


[features]
default = ["defmt"]
defmt = ["dep:defmt", "embassy-nrf/defmt", "heapless/defmt-03"]
trouble = ["embassy-nrf/unstable-pac", "embassy-nrf/rt", "nrf-sdc", "nrf-mpsl", "static_cell"]

[patch.crates-io]
nrf-sdc = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "3702af909d31cd81c62f15e1aa9d5f637ec935fa" }
nrf-mpsl = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "3702af909d31cd81c62f15e1aa9d5f637ec935fa" }